### ISSUE TITLE
Can't understand the formulation of ExactRHS in Module 2

### ISSUE THREAD

**Issue by jingchangshi** [userjjb/22_6xx-DG-for-PDEs#1]
I've watched your youtube tutorial on DG and cloned this git repo. Thank you for the excellent explanation.

What I'm concerned is your demo MATLAB script in module 2.

In the demo script, I can't understant why you formulate ExactRHS such way:

```
ExactRHS(1, :) = ...
    ( tau * deltax .* cos(tau * xNode(1:end-1)) ...
    + sin(tau * xNode(1:end-1)) ...
    - sin(tau * xNode(2:end)) ) ...
        ./ ( 4 * pi^2 * (deltax) );
ExactRHS(2, :) = ...
    -( tau * deltax .* cos(tau * xNode(2:end)) ...
    + sin(tau * xNode(1:end-1)) ...
    - sin(tau * xNode(2:end)) ) ...
        ./ ( 4 * pi^2 * (deltax) );
```

I know that the key idea behind the above is that $\int u_h \phi = \int u_0 \phi$. According to my understanding, I would like to formulate as follows,

```
f1 = @(x) - sin(2*pi*x)/(4*pi^2) - (cos(2*pi*x)/2 - (x*cos(2*pi*x))/2)/pi;
f1_int = zeros(K, 1);
for i = 1 : K
    x_init = xNode(i);
    x_end = xNode(i+1);
    f1_int(i) = f1(x_end) - f1(x_init);
end
f2 = @(x) (sin(2*pi*x) - 2*pi*x*cos(2*pi*x))/(4*pi^2);
f2_int = zeros(K, 1);
for i = 1 : K
    x_init = xNode(i);
    x_end = xNode(i+1);
    f2_int(i) = f2(x_end) - f2(x_init);
end
```

They are the integral of $\int u_0 \phi$ and the definite integral is over every single element. However, the above formulations give different result.

The plot of your formulation is

![rhs](https://cloud.githubusercontent.com/assets/9106886/13776805/0f9448fa-eae7-11e5-867d-df7bcdc1711e.png)

While my formulation output as follows,

![f](https://cloud.githubusercontent.com/assets/9106886/13776817/20f9dad8-eae7-11e5-9c6e-729a64aaa399.png)

Could you point out why I'm wrong? Thanks!

**Comment by userjjb** [comment]
Fortunately it seems your error is a simple one:
While it wasn't immediately clear what your f1() and f2() functions were, I assumed they were the indefinite integrals of \int u0 \phi where the initial condition continues to be the one i used u0=sin(2*pi*x); you are calculating the definite integral by evaluating the indefinite at the edges of each element (correct me if I misstated your intent). 

A quick derivative of f1 and f2 yielded: x*sin(2*pi*x) and (x-1)*sin(2*pi*x). It seems you have incorrectly set up your \phi functions and missed a perhaps subtle point. The linear basis functions of the test function are defined **locally** on **each** element and the RHS integral is performed over **just** the range of that element.

An easy way to explain the distinction is to treat each element as a separate entity; the basis function is defined **only** over the element, the basis function should be 0 on one end and 1 on the other. While our **global** domain spans from (in this case) 0<x<1, each element only spans a piece of this: say A to B. For example if we split the domain into 10 pieces, the second element would range from x=0.1 to 0.2. If one were to use simply 'x' and 'x-1' for the basis functions it is easy to see they would not attain the proper values at the element bounds. Instead the correct functions should be (x-A)/(B-A) and (B-x)/(B-A), respectively.

Armed with this knowledge you should see why your f1() and f2() wouldn't work, they were using the wrong basis functions. The correct definite integral for f1() is given by [Wolfram as this](https://www.wolframalpha.com/input/?i=integrate+sin%282*pi*x%29*%28%28x-A%29%2F%28B-A%29%29+dx+x%3DA..B). One can find the second integral the same way. Note that the Wolfram definite integral result is precisely the one used in the code. Be sure to note that while the basis function may be locally defined, the initial condition is globally specified so we don't need to do anything to sin(2*pi*x) on a per element basis.

There are a couple further points to make that are relevant. In some ways this is the "wrong" way to calculate 'uh', analytical functions describing initial conditions in the "real world" are rare and analytical integrals of these existing are even rarer. However the intention is to lean on familiar calculus for most students. It might be a pain in the butt to find, but the analytical integral is familiar territory.

The "right way" to find 'uh' would be to numerically calculate it. One could do this in Matlab with:
ExactRHS(1,N)=integral( @(x) sin(tau_x)_(x-A)/(B-A), A, B)
where N is the element number and A and B are it's bounds. This is a bit overkill and is Matlab specific, the more general way would be to to use something like a Gauss-Legendre quadrature (when you get to module 3 you will see this in action). This is considered a "modal" approach to finding the approximate initial conditions. Perhaps even easier is to take a "nodal" approach, this is how things proceed in Module 3. The distinction at 1st order between nodal and modal is blurred as they are almost the same thing.

One final point: crucially your functions are missing 'deltax' entirely. This should tip you off as something being wrong; surely if the element size changes the value of the integral must as well. The broader statement to be made is we are actually _mapping_ our "physical" element (A to B) to a "computational" element (0 to 1). This mapping generates an additional constant that is multiplied by our integral to compensate for the mapping. In general you will see this called the Jacobian (or the determinant of the Jacobian matrix depending on the author). The Jacobian isn't terribly exciting at 1D, but is more involved for multidimensional formulations with non-constant sized/shaped elements.

Thanks for the question, keep them coming!

**Comment by jingchangshi** [comment]
Thank you! It's very nice of you to give such detailed explanation. I failed for misunderstanding the basis funtions defined locally.
