### ISSUE TITLE
There maybe some errors in Module 3B

### ISSUE THREAD

**Issue by jingchangshi** [userjjb/22_6xx-DG-for-PDEs#2]
I directly execute the script `SC1DLeg.m` and get the following error

```
>> SC1DLeg
Error using toeplitz (line 23)
Inputs must be numeric.

Error in SC1DLeg (line 86)
SelfStencil = 2*(toeplitz(mod(0:N,2),0:N<0))-ones(N+1);
```

I suppose the input parameters for toeplitz maybe be wrong. Please check.

**Comment by userjjb** [comment]
What version of Matlab are you using? Everything has been tested under Matlab 2012b.

**Comment by jingchangshi** [comment]
@userjjb 
I'm using R2013a, Linux x64
![matlab](https://cloud.githubusercontent.com/assets/9106886/13902636/26e6d6ec-ee8b-11e5-9d02-e33f0d192e3d.png)

**Comment by jingchangshi** [comment]
@userjjb 
What does this `0:N<0` means?

**Comment by userjjb** [comment]
Thanks for your version, I'll see if anything was changed about toeplitz(). What value of N did this error occur for?

0:N<0 does the same thing as zeros(1,N)

**Comment by jingchangshi** [comment]
@userjjb Thank you! I change `0:N<0` to be `zeros(1, N+1)`, and the script works well. In your current code, `N=5`.

The result:

![Uploading result.png…]()
